services:
  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:v24.3.10
    container_name: redpanda
    command:
      - redpanda
      - start
      - --smp
      - '1'
      - --reserve-memory
      - 0M
      - --overprovisioned
      - --node-id
      - '0'
      - --kafka-addr
      - PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      - --advertise-kafka-addr
      - PLAINTEXT://redpanda:29092,OUTSIDE://localhost:9092
    ports:
      - "9092:9092"
      - "29092:29092"
      - "9644:9644"
    volumes:
      - redpanda-data:/var/lib/redpanda/data

  init:
    image: docker.redpanda.com/redpandadata/redpanda:v24.3.10
    container_name: redpanda-init
    depends_on:
      - redpanda
    command: |
      bash -c '
        rpk cluster health --api-urls http://redpanda:9644 &&
        rpk topic create test-topic --partitions 1 --replicas 1
      '

volumes:
  redpanda-data: 